data_path:     ../../Data/PolishData
output_path:   ../../Data/PolishData-triann
cpc_path:      ./cpc
sampling_rate: 16000
top_db:        60
n_mels:        80
n_fft:         400
n_shift:       160
win_length:    400
window:        hann
fmin:          80
fmax:          7600
s2s_portion:   0.1
eval_spks:     1 # we can specify the test speakers
num_samples:   300 # number of sample pairs


